version: '3'
services:
  postgres-db:
    image: postgres:12
    env_file:
      - '../.env.docker'
    ports:
      - '5442:5432'
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
